train:
  _target_: src.datasets.dla_avss
  input_length: 1024
  dataset_length: 15
  limit: 10
  part: "train"
val:
  _target_: src.datasets.dla_avss
  input_length: 1024
  dataset_length: 15
  limit: 10
  part: "val"
