device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.SI_SNRi
    device: ${metrics.device}
    name: "TRAIN_SI-SNRi" # just an example to see difference
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SI_SNRi
    device: ${metrics.device}
    num_speakers: 2
    name: "SI-SNRi"
  - _target_: src.metrics.SDRi
    device: ${metrics.device}
    name: "SDRi"
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    fs: 16000
    mode: "wb"
    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    fs: 16000
    name: "STOI"