_target_: src.logger.WandBWriter
# project_name: "audio-visual-source-separation"
project_name: "test"
entity: null
run_name: "conv_tasnet"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
